// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSketch.Svg")>]
[<assembly: AssemblyProductAttribute("FSketch")>]
[<assembly: AssemblyDescriptionAttribute("Yet another drawing DSL in F#")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSketch.Svg"
    let [<Literal>] AssemblyProduct = "FSketch"
    let [<Literal>] AssemblyDescription = "Yet another drawing DSL in F#"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
