// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSketch")>]
[<assembly: AssemblyProductAttribute("FSketch")>]
[<assembly: AssemblyDescriptionAttribute("Yet another drawing DSL in F#")>]
[<assembly: AssemblyVersionAttribute("0.0.4")>]
[<assembly: AssemblyFileVersionAttribute("0.0.4")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSketch"
    let [<Literal>] AssemblyProduct = "FSketch"
    let [<Literal>] AssemblyDescription = "Yet another drawing DSL in F#"
    let [<Literal>] AssemblyVersion = "0.0.4"
    let [<Literal>] AssemblyFileVersion = "0.0.4"
    let [<Literal>] AssemblyConfiguration = "Release"
