// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSketch.Winforms")>]
[<assembly: AssemblyProductAttribute("FSketch")>]
[<assembly: AssemblyDescriptionAttribute("Yet another drawing DSL in F#")>]
[<assembly: AssemblyVersionAttribute("0.0.9")>]
[<assembly: AssemblyFileVersionAttribute("0.0.9")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSketch.Winforms"
    let [<Literal>] AssemblyProduct = "FSketch"
    let [<Literal>] AssemblyDescription = "Yet another drawing DSL in F#"
    let [<Literal>] AssemblyVersion = "0.0.9"
    let [<Literal>] AssemblyFileVersion = "0.0.9"
    let [<Literal>] AssemblyConfiguration = "Release"
